#if !canImport(ObjectiveC)
import XCTest

extension FilesystemValueProviderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FilesystemValueProviderTests = [
        ("testCounter", testCounter),
        ("testDict", testDict),
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FilesystemValueProviderTests.__allTests__FilesystemValueProviderTests),
    ]
}
#endif
